### PR TITLE
allow to save into a writer + correct fix on emissions to water

### PR DESCRIPTION
**Pull request by AlbanSeurat**

### CODE REVIEW

**Comment by msrocka** [comment]
Many thanks for your pull request; merged it. I have one question regarding the integer conversion in the `putDouble` method: is it just to make the output more readable or is there also another reason?

```java
public CsvBuffer putDouble(double d) {
  var s = d == (int) d 
    ? Integer.toString((int)d)
    : Double.toString(d);
  return putString(decimalPoint(s));
}
```

Also, we can skip the `decimalPoint` in the integer case then. I will upload a new release to the Maven Central later this week.

**Comment by AlbanSeurat** [comment]
The change is to reflect simapro behaviour where it generate integer when there is no decimal value.

**Comment by AlbanSeurat** [comment]
Any chance to have the 3.0.3 deployed today ?

**Comment by msrocka** [comment]
just released it: https://repo1.maven.org/maven2/org/openlca/olca-simapro-csv/3.0.3/

**Comment by AlbanSeurat** [comment]
Thanks!

**Pull request merged**
